# Generated by Django 5.1.7 on 2025-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
